
[id="con-aap-installation-on-disconnected-rhel_{context}"]

= {PlatformNameShort} installation on disconnected RHEL

[role="_abstract"]
You can install {PlatformNameShort} {ControllerName} and {PrivateHubName} without an internet connection by using the installation setup bundle instead of the standard installer. The setup bundle includes additional components that make installing {PlatformNameShort} easier in a disconnected environment. These include the {PlatformNameShort} software packages (RPMs), the default {ExecEnvShort} (EE) images, and a curated set of certified Ansible content collections.

== System requirements for disconnected installation

Ensure that your system has all the hardware requirements before performing a disconnected installation of {PlatformNameShort}. For more information about hardware requirements, see link:{BaseURL}/red_hat_ansible_automation_platform/{PlatformVers}/html-single/red_hat_ansible_automation_platform_installation_guide/index#platform-system-requirements[Chapter 2. System requirements].

== RPM Source

RPM dependencies for {PlatformNameShort} that come from the RHEL BaseOS and AppStream repositories are not included in the setup bundle. If you already have a Red Hat Satellite Server in your disconnected environment, each {PlatformNameShort} RHEL server ({ControllerName}, {PrivateNubName}, and so on) should be subcribed to your Satellite Server for access to the BaseOS and AppStream repositories.  If a Satellite Server is not available, you can choose between the following options:

* Reposync
* The RHEL Binary DVD

[NOTE]

====
The RHEL Binary DVD method requires the DVD for supported versions of RHEL, including version 8.6 or higher. See link:https://access.redhat.com/support/policy/updates/errata[Red Hat Enterprise Linux Life Cycle] for information about which versions of RHEL are currently supported.
====

.Additional Resources
* link:{BaseURL}/red_hat_satellite/{SatelliteVers}/html/installing_satellite_server_in_a_disconnected_network_environment/index[Satellite]
