// this info is duplicated here: {BaseURL}/red_hat_ansible_automation_platform/1.2/html/installing_and_upgrading_private_automation_hub/installing_online_or_offline#doc-wrapper

[id="installing-the-aap-setup-bundle_{context}"]

= Downloading and installing the {PlatformNameShort} setup bundle

[role="_abstract"]
Choose the setup bundle to download {PlatformNameShort} for disconnected installations. This bundle includes the RPM content for {PlatformNameShort} and the default {ExecEnvShort} images that will be uploaded to your {PrivateHubName} during the installation process.

The xref:ref-single-controller-hub-ext-database-inventory[Single {ControllerName} and single {HubName} with external (installer managed) database] installation scenario is recommended for disconnected installations.  On a disconnected network, the {HubName} will provide a repository for {ExecEnvShort} (EE) images and Ansible content collections that are normally available from internet-connected locations. The installer bundle will copy the default EE images to the {HubName}, as well as a set of certified collections for supporting common automation use cases.

[NOTE]
====
The `registry_url`, `registry_username`, and `registry_password` installation file variables are not required when installing in and disconnected environment, see xref:con-install-scenario-recommendations[]
====


.Procedure

. Download the {PlatformNameShort} setup bundle package by navigating to the link:{PlatformDownloadUrl}[{PlatformName} download] page and clicking btn:[Download Now] for the {PlatformNameShort} {PlatformVers} Setup Bundle.

. From {ControllerName}, untar the bundle:
+
----
$ tar xvf \
   ansible-automation-platform-setup-bundle-2.4-1.tar.gz
$ cd ansible-automation-platform-setup-bundle-2.4-1
----
+
. Edit the inventory file to include the required options:

.. `automationcontroller` host group
.. `automationhub` host group
.. `database` host group
.. `admin_password` variable
.. `pg_host` and `pg_port` variables
.. `pg_password` variable
.. `automationhub_admin_password` variable
.. `automationhub_pg_host` and `automationhub_pg_port` variables
.. `automationhub_pg_password` variable
+
*Example Inventory file*
+
----
[automationcontroller]
automationcontroller.example.org

[automationhub]
automationhub.example.org

[database]
aapdatabase.example.org

[all:vars]
admin_password='password123'

pg_host='aapdatabase.example.org'
pg_port=5432
pg_database='awx'
pg_username='awx'
pg_password='dbpassword123'
pg_sslmode='prefer'  # set to 'verify-full' for client-side enforced SSL

automationhub_admin_password='hubpassword123'
automationhub_pg_host='aapdatabase.example.org'
automationhub_pg_port=5432
automationhub_pg_database='automationhub'
automationhub_pg_username='automationhub'
automationhub_pg_password='dbpassword123'
automationhub_pg_sslmode='prefer'
----
+
. Run the {PlatformNameShort} setup bundle executable as the root user:
+
----
$ sudo -i
# cd /path/to/ansible-automation-platform-setup-bundle-2.4-1
# ./setup.sh
----
+
. When installation is complete, navigate to the Fully Qualified Domain Name (FQDN) for the {ControllerName} node that was specified in the installation inventory file.

. Log in using the administrator credentials specified in the installation inventory file.

[NOTE]
====
The inventory file must be kept intact after installation because it is used for backup, restore, and upgrade functions. Keep a backup copy in a secure location, given that the inventory file contains passwords.
====
